services:
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: monai
      POSTGRES_PASSWORD: monai
      POSTGRES_DB: monai_devops
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
